### ISSUE TITLE
[User Error] Emoji9 with absence of a valid font.

### ISSUE THREAD

**Issue by i-Masoud** [PoomSmart/EmojiPort-Fix#1]
Hello dear friend. I have installed the latest version (1.1.1) and there are still bugs in the iPhone 6 Plus
![image](https://cloud.githubusercontent.com/assets/20161417/16370303/ce2abfb6-3c53-11e6-8763-37a29d623935.jpg)

**Comment by PoomSmart** [comment]
Because you did not install iOS 9.3 Emoji font from Cydia.

**Comment by i-Masoud** [comment]
The problem was fixed..👍🏼
Thank you for your attention
